name: torchomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - numpy==1.21
  - pytorch
  - python-lsp-server
  - libblas=*=*_mkl
  - pytest
  - python=3
  - scipy
  - gitpython
  - pip:
    - genomic-benchmarks
