name: dna2prot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # project-specific packages
  - numpy==1.21
  - biopython
  - pyprojroot
  - pytorch
  - pytorch-lightning
  - python-lsp-server
  - jupytext
  - torchvision
  - umap-learn
  # required
  - ipython
  - ipywidgets
  - jupyterlab
  - libblas=*=*_mkl
  - nextflow
  - pytest
  - python=3
  # usually good to have
  - gitpython
  - pandas
  - scikit-learn
  - scikit-learn-intelex
