name: dna2prot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # project-specific packages
  - numpy==1.21
  - biopython
  - pyprojroot
  - pytorch
  - pytorch_lightning
  - jupytext
  - torchvision
  - umap-learn
  - pip:
      - zenodo_get
  # required
  - dvc
  - dvc-gdrive
  - ipython
  - ipywidgets
  - jupyterlab
  - libblas=*=*_mkl
  - nextflow
  - pip
  - pytest
  - python=3
  - r-irkernel
  # usually good to have
  - gitpython
  - r
  - rpy2
  - r-tidyverse
  - pandas
  - scikit-learn
  - scikit-learn-intelex
  - seaborn
