name: dna2prot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # project-specific packages
  - biopython
  - pytorch
  - torchvision
  - torchinfo
  - pip:
      - zenodo_get
  # required
  - codecov
  - dvc
  - dvc-gdrive
  - ipython
  - ipywidgets
  - jupyterlab
  - jupyter_contrib_nbextensions
  - libblas=*=*_mkl
  - nextflow
  - pip
  - pytest
  - python=3
  - r-irkernel
  # usually good to have
  - jax
  - r
  - rpy2
  - r-tidyverse
  - pandas
  - scikit-learn
  - scikit-learn-intelex
  - seaborn
